#!/bin/sh
# this script helps to compile tests without running them

# allow to specify which command to prepend to tests
if test "$TDS_MAKEENVS_CMD" = ""; then
	TDS_MAKEENVS_CMD=true
fi

# old style autoconf, just override TESTS_ENVIRONMENT with true to avoid
# doing tests but just compile
if test "$1" != "/bin/sh" -a "$1" != "/bin/bash"; then
	$TDS_MAKEENVS_CMD "$@"
	exit $?
fi

# new style, there is a test driver between
# put the "true" comand in the right position (after "--")
# old shells does not support additional arrays so use arguments one
# basically we construct the new array at the end of original one
for arg
do
	case "$arg" in
	--)
		set a "$@" "$arg" $TDS_MAKEENVS_CMD
		;;
	*)
		set a "$@" "$arg"
		;;
	esac
	# remove "a"
	shift
	# remove original argument, so at the end all original
	# arguments are removed
	shift
done

exec "$@"
