tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
ports:
  - port: 5000
    onOpen: ignore
  - port: 5601
    onOpen: open-browser
  - port: 9200
    onOpen: open-preview
  - port: 9300
    onOpen: ignore
  - port: 9600
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - ms-vscode.cpptools
    - eamodio.gitlens
    - mhutchie.git-graph