
#undef BSD_COMP

#undef INADDR_NONE

#undef HAVE_FUNC_GETHOSTBYNAME_R_3

#undef HAVE_FUNC_GETHOSTBYNAME_R_5

#undef HAVE_FUNC_GETHOSTBYNAME_R_6

#undef HAVE_FUNC_GETSERVBYNAME_R_4

#undef HAVE_FUNC_GETSERVBYNAME_R_5

#undef HAVE_FUNC_GETSERVBYNAME_R_6

#undef HAVE_FUNC_GETHOSTBYADDR_R_5

#undef HAVE_FUNC_GETHOSTBYADDR_R_7

#undef HAVE_FUNC_GETHOSTBYADDR_R_8

#undef HAVE_INT64

#undef HAVE_READLINE
