/* include/config.h.  Generated by configure.  */
/* include/config.h.in.  Generated from configure.in by autoheader.  */

/* Define to 1 if you need BSD_COMP defined to get FIONBIO defined. */
/* #undef BSD_COMP */

/* Define to enable work in progress code */
/* #undef ENABLE_DEVELOPING 1 */

/* Define to enable extra checks on code */
/* #undef ENABLE_EXTRA_CHECKS 1 */

/* Define to 1 if you have the <arpa/inet.h> header file. */
/* #undef HAVE_ARPA_INET_H */

/* Define to 1 if you have the `asprintf' function. */
/* #undef HAVE_ASPRINTF */

/* Define to 1 if you have the `atoll' function. */
#define HAVE_ATOLL 1

/* Define to 1 if you have the <dlfcn.h> header file. */
/* #undef HAVE_DLFCN_H */

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if your system provides the 5-parameter version of
   gethostbyaddr_r(). */
/* #undef HAVE_FUNC_GETHOSTBYADDR_R_5 */

/* Define to 1 if your system provides the 6-parameter version of
   gethostbyaddr_r(). */
/* #undef HAVE_FUNC_GETHOSTBYADDR_R_7 */

/* Define to 1 if your system provides the 8-parameter version of
   gethostbyaddr_r(). */
/* #undef HAVE_FUNC_GETHOSTBYADDR_R_8 */

/* Define to 1 if your system provides the 3-parameter version of
   gethostbyname_r(). */
/* #undef HAVE_FUNC_GETHOSTBYNAME_R_3 */

/* Define to 1 if your system provides the 5-parameter version of
   gethostbyname_r(). */
/* #undef HAVE_FUNC_GETHOSTBYNAME_R_5 */

/* Define to 1 if your system provides the 6-parameter version of
   gethostbyname_r(). */
/* #undef HAVE_FUNC_GETHOSTBYNAME_R_6 */

/* Define to 1 if your system provides the 4-parameter version of
   getservbyname_r(). */
/* #undef HAVE_FUNC_GETSERVBYNAME_R_4 */

/* Define to 1 if your system provides the 5-parameter version of
   getservbyname_r(). */
/* #undef HAVE_FUNC_GETSERVBYNAME_R_5 */

/* Define to 1 if your system provides the 6-parameter version of
   getservbyname_r(). */
/* #undef HAVE_FUNC_GETSERVBYNAME_R_6 */

/* Define to 1 if you have the `gethostent_r' function. */
/* #undef HAVE_GETHOSTENT_R */

/* Define to 1 if you have the `gethostname' function. */
#define HAVE_GETHOSTNAME 1

/* Define to 1 if you have the `getpwuid' function. */
/* #undef HAVE_GETPWUID */

/* Define to 1 if you have the `getpwuid_r' function. */
/* #undef HAVE_GETPWUID_R */

/* Define to 1 if you have the `gettimeofday' function. */
/* #undef HAVE_GETTIMEOFDAY */

/* Define to 1 if you have the `getuid' function. */
/* #undef HAVE_GETUID */

/* Define if you have the iconv() function. */
/* #undef HAVE_ICONV */

/* Define to 1 if you have a 64-bit integral type. */
#define HAVE_INT64 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if your system provides the malloc_options variable. */
/* #undef HAVE_MALLOC_OPTIONS */

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <netdb.h> header file. */
/* #undef HAVE_NETDB_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
/* #undef HAVE_NETINET_IN_H */

/* Define to 1 if you have the <paths.h> header file. */
/* #undef HAVE_PATHS_H */

/* Define to 1 if you have the GNU Readline library. */
/* #undef HAVE_READLINE */

/* Define to 1 if you have the `sethostent_r' function. */
/* #undef HAVE_SETHOSTENT_R */

/* Define to 1 if you have the SQLGetPrivateProfileString function. */
#define HAVE_SQLGETPRIVATEPROFILESTRING 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
/* #undef HAVE_STRINGS_H */

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the `strtok_r' function. */
/* #undef HAVE_STRTOK_R */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
/* #undef HAVE_SYS_IOCTL_H */

/* Define to 1 if you have the <sys/param.h> header file. */
/* #undef HAVE_SYS_PARAM_H */

/* Define to 1 if you have the <sys/socket.h> header file. */
/* #define HAVE_SYS_SOCKET_H 1 */

/* Define to 1 if you have the <sys/stat.h> header file. */
/* #undef HAVE_SYS_STAT_H */

/* Define to 1 if you have the <sys/time.h> header file. */
#ifdef __GNUC__
# define HAVE_SYS_TIME_H 1
#endif

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
/* #undef HAVE_UNISTD_H */

/* Define to 1 if you have the `vasprintf' function. */
/* #undef HAVE_VASPRINTF */

/* Define to 1 if you have the `vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define as const if the declaration of iconv() needs const. */
#define ICONV_CONST const

/* Define to value of INADDR_NONE if not provided by your system header files.
   */
/* #undef INADDR_NONE */

/* Define to 1 if the BSD-style netdb interface is reentrant. */
#define NETDB_REENTRANT 1

/* Name of package */
#define PACKAGE "freetds"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* The size of a `char', as computed by sizeof. */
#define SIZEOF_CHAR 1

/* The size of a `double', as computed by sizeof. */
#define SIZEOF_DOUBLE 8

/* The size of a `float', as computed by sizeof. */
#define SIZEOF_FLOAT 4

/* The size of a `int', as computed by sizeof. */
#define SIZEOF_INT 4

/* The size of a `long', as computed by sizeof. */
#define SIZEOF_LONG 4

/* The size of a `long long', as computed by sizeof. */
#define SIZEOF_LONG_LONG 0

/* The size of a `short', as computed by sizeof. */
#define SIZEOF_SHORT 2

/* The size of a `__int64', as computed by sizeof. */
#define SIZEOF___INT64 8

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Define to 1 if you can safely include both <sys/time.h> and <time.h>. */
#ifdef __GNUC__
# define TIME_WITH_SYS_TIME 1
#else
# define TIME_WITH_SYS_TIME 0
#endif

/* Version number of package */
#define VERSION "0.63"

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef WORDS_BIGENDIAN */

/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif

#undef HAVE_ODBCSS_H
#ifdef _MSC_VER
#define HAVE_ODBCSS_H 1
#endif

#define TDS42 1

#ifdef _MSC_VER
#define inline __inline
#endif

